title: NHS Citizen Experience Architecture - Staging
email: ross.buggins@nhs.net
description: >- # this means to ignore newlines until "baseurl:"
  NHS Transformation Directorate, NHS England and Improvement. Giving patients, service users and carers the tools to access information and services directly.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  rossbugginsnhs


published_url: "https://rossbuggins.nhsei.xyz"
gh_action_build_file_name: "azure-static-web-apps-blue-beach-03e72e403.yml"
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/RossBugginsNHS/nhs-experience" # the github URL for your repo
gh_edit_branch: "latest" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
gh_repo_owner: "Ross Buggins"